import { HeaderRow } from "./row";
import { CellContentType } from "./cell-content-type";
import { TableUtils } from "./table-utils";

/**
 * Options that influence how header rows are parsed and normalised.
 */
export type HeaderRowOptions = {
	/** How to extract text from header cells (innerText by default). */
	cellContentType?: CellContentType;
	/** Replaces empty header cells with a fallback token when enabled. */
	emptyCellReplacement?: boolean;
	/** Adds suffixes to duplicate header labels to keep them unique. */
	duplicateSuffix?: boolean;
	/** Controls how automatically generated colspan placeholders are handled. */
	colspan?: {
		/** Removes generated placeholder columns when disabled. */
		enabled?: boolean;
		/** Preserves the autogenerated suffix (e.g. `__C1`) when enabled. */
		suffix?: boolean;
	};
};

type RequiredHeaderRowOptions = Required<HeaderRowOptions> & {
	colspan: Required<NonNullable<HeaderRowOptions["colspan"]>>;
};

/**
 * Converts DOM header rows into flattened header arrays while honouring row/col spans.
 */
export abstract class TableHeader {
	/**
	 * Parses the supplied header rows and applies all configured post-processing options.
	 *
	 * @param headerRows - DOM rows taken from the table head section.
	 * @param columnSelector - Selector used to read individual header cells.
	 * @param options - Optional configuration controlling text extraction and suffix behaviour.
	 * @returns Normalized header rows with span information resolved.
	 */
	static getRows(
		headerRows: Element[],
		columnSelector: string,
		options?: HeaderRowOptions
	): HeaderRow[] {
		const resolvedOptions = this.resolveOptions(options);
		const headerRowValues: HeaderRow[] = [];
		const rowSpans = new Map<number, string>();

		for (const headerRow of headerRows) {
			const rowValues = this.extractRow(
				headerRow,
				columnSelector,
				rowSpans,
				resolvedOptions
			);
			headerRowValues.push(rowValues);
		}

		this.applyColspanOptions(headerRowValues, resolvedOptions);
		this.applyDuplicateSuffix(headerRowValues, resolvedOptions);

		return headerRowValues;
	}

	/**
	 * Builds a fully populated options object from potentially partial user input.
	 *
	 * @param options - The optional user-supplied header parsing configuration.
	 * @returns A resolved configuration with defaults filled in.
	 */
	private static resolveOptions(
		options?: HeaderRowOptions
	): RequiredHeaderRowOptions {
		return {
			cellContentType: options?.cellContentType ?? CellContentType.InnerText,
			emptyCellReplacement: options?.emptyCellReplacement ?? false,
			duplicateSuffix: options?.duplicateSuffix ?? false,
			colspan: {
				enabled: options?.colspan?.enabled ?? false,
				suffix: options?.colspan?.suffix ?? false,
			},
		};
	}

	/**
	 * Extracts the content for a single header row and accounts for row spans that bleed into subsequent columns.
	 *
	 * @param row - The DOM header row to process.
	 * @param columnSelector - Selector used to locate header cells inside the row.
	 * @param rowSpans - Map tracking cells that span into the current row.
	 * @param options - The resolved header parsing options.
	 * @returns The flattened header row content.
	 */
	private static extractRow(
		row: Element,
		columnSelector: string,
		rowSpans: Map<number, string>,
		options: RequiredHeaderRowOptions
	): HeaderRow {
		const headerRow: HeaderRow = [];
		const cells = Array.from(row.querySelectorAll(columnSelector));
		let columnIndex = 0;

		for (const cell of cells) {
			columnIndex = this.processCell(
				cell,
				headerRow,
				rowSpans,
				columnIndex,
				options
			);
		}

		this.appendRemainingRowSpans(headerRow, rowSpans, columnIndex);
		return headerRow;
	}

	/**
	 * Normalises a header cell into the output array and updates span bookkeeping.
	 *
	 * @param cell - The header cell element currently being converted.
	 * @param headerRow - Mutable array representing the flattened header row.
	 * @param rowSpans - Row span registry shared across rows while building the header.
	 * @param columnIndex - Current output index for the row.
	 * @param options - Resolved parsing options.
	 * @returns The next column index to use after the cell has been handled.
	 */
	private static processCell(
		cell: Element,
		headerRow: HeaderRow,
		rowSpans: Map<number, string>,
		columnIndex: number,
		options: RequiredHeaderRowOptions
	): number {
		while (rowSpans.has(columnIndex)) {
			headerRow.push(rowSpans.get(columnIndex)!);
			rowSpans.delete(columnIndex);
			columnIndex++;
		}

		let text = TableUtils.getCellContent(cell, options.cellContentType);
		if (!text && options.emptyCellReplacement) {
			text = "{{Empty}}";
		}

		const { colspan, rowspan } = TableUtils.parseSpanAttributes(cell);

		headerRow.push(text);
		this.handleColspan(headerRow, text, colspan);
		this.handleRowspan(rowSpans, text, columnIndex, colspan, rowspan);

		return columnIndex + colspan;
	}

	/**
	 * Adds autogenerated placeholder headers for columns created by a colspan.
	 *
	 * @param headerRow - The header row being built.
	 * @param text - Base header text for the column.
	 * @param colspan - Number of columns spanned by the current cell.
	 */
	private static handleColspan(
		headerRow: HeaderRow,
		text: string,
		colspan: number
	): void {
		for (let i = 1; i < colspan; i++) {
			headerRow.push(`${text}__C${i}`);
		}
	}

	/**
	 * Records row span information so future rows inject the repeated header values automatically.
	 *
	 * @param rowSpans - Global row span registry keyed by column index.
	 * @param text - Text to repeat for spanned rows.
	 * @param columnIndex - Index of the current column.
	 * @param colspan - Number of columns the cell spans.
	 * @param rowspan - Number of rows the cell spans into.
	 */
	private static handleRowspan(
		rowSpans: Map<number, string>,
		text: string,
		columnIndex: number,
		colspan: number,
		rowspan: number
	): void {
		if (rowspan <= 1) {
			return;
		}

		for (let i = 0; i < colspan; i++) {
			rowSpans.set(columnIndex + i, text);
		}
	}

	/**
	 * Appends any outstanding row span values once the explicit cells have been processed.
	 *
	 * @param headerRow - The header row being finalised.
	 * @param rowSpans - Registry of outstanding row span entries.
	 * @param columnIndex - Column index to begin checking from.
	 */
	private static appendRemainingRowSpans(
		headerRow: HeaderRow,
		rowSpans: Map<number, string>,
		columnIndex: number
	): void {
		while (rowSpans.has(columnIndex)) {
			headerRow.push(rowSpans.get(columnIndex)!);
			rowSpans.delete(columnIndex);
			columnIndex++;
		}
	}

	/**
	 * Applies the configured colspan behaviours, either removing or renaming generated placeholder headers.
	 *
	 * @param headerRows - All parsed header rows to mutate.
	 * @param options - Resolved colspan options.
	 */
	private static applyColspanOptions(
		headerRows: HeaderRow[],
		options: RequiredHeaderRowOptions
	): void {
		if (!options.colspan.enabled) {
			for (const row of headerRows) {
				for (let i = 0; i < row.length; i++) {
					if (/__C\d/.test(row[i])) {
						row.splice(i, 1);
						i--;
					}
				}
			}
		}

		if (!options.colspan.suffix) {
			for (const row of headerRows) {
				for (let i = 0; i < row.length; i++) {
					if (/__C\d/.test(row[i])) {
						row[i] = row[i].replace(/__C\d/, "");
					}
				}
			}
		}
	}

	/**
	 * Adds duplicate suffixes to headers that appear more than once, when requested.
	 *
	 * @param headerRows - The parsed header rows to update.
	 * @param options - Resolved header options.
	 */
	private static applyDuplicateSuffix(
		headerRows: HeaderRow[],
		options: RequiredHeaderRowOptions
	): void {
		if (!options.duplicateSuffix) {
			return;
		}

		for (const row of headerRows) {
			const seen = new Map<string, number>();
			for (let i = 0; i < row.length; i++) {
				const header = row[i];
				const count = seen.get(header) ?? 0;
				if (count > 0) {
					row[i] = `${header}__D${count}`;
				}
				seen.set(header, count + 1);
			}
		}
	}
}
